name: Deploy Backend to Render

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'server/**'

jobs:
  deploy:
    name: Trigger Render Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set Deploy Hook
        id: hook
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "url=${{ secrets.RENDER_DEPLOY_HOOK }}" >> $GITHUB_OUTPUT
          elif [ "${GITHUB_REF##*/}" = "test" ]; then
            echo "url=${{ secrets.RENDER_TEST_DEPLOY_HOOK }}" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Webhook
        run: curl -X POST "${{ steps.hook.outputs.url }}"